# Generated by Django 3.0.6 on 2020-08-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes',
        ),
    ]
