# Generated by Django 3.0.6 on 2020-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0007_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'post')},
        ),
    ]
