# Generated by Django 3.0.6 on 2020-08-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0009_auto_20200820_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
    ]
