# Generated by Django 3.0.6 on 2020-08-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0010_auto_20200821_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'post')},
        ),
    ]
