# Generated by Django 3.0.6 on 2020-08-22 08:52

import blog_apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0011_auto_20200821_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blog_apis.models.upload_to),
        ),
    ]
