# Generated by Django 3.0.6 on 2020-08-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0013_auto_20200822_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_apis.BlogPictures'),
        ),
    ]
