# Generated by Django 3.0.6 on 2020-08-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0014_auto_20200822_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_picture',
        ),
        migrations.AddField(
            model_name='blogpictures',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_apis.BlogModel'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpictures',
            unique_together={('image', 'blog')},
        ),
    ]
