# Generated by Django 3.0.6 on 2020-09-09 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apis', '0017_auto_20200829_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 15, 16, 1, 592739, tzinfo=utc)),
        ),
    ]
